Transform: AWS::Serverless-2016-10-31

Parameters:
  transcribeName:
    Type: String
  mediaConvertName:
    Type: String

Resources:
  StateMachine5b3433f1:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: 영상 변환 및 분석
        StartAt: ParallelAnalysis
        States:
          ParallelAnalysis:
            Type: Parallel
            Branches:
              - StartAt: Transcribe
                States:
                  Transcribe:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    Retry:
                      - ErrorEquals:
                          - Lambda.ServiceException
                          - Lambda.AWSLambdaException
                          - Lambda.SdkClientException
                          - Lambda.TooManyRequestsException
                        IntervalSeconds: 1
                        MaxAttempts: 3
                        BackoffRate: 2
                        JitterStrategy: FULL
                    TimeoutSeconds: 300
                    Parameters:
                      FunctionName: !Ref transcribeName
                      Payload.$: $
                    End: true
              - StartAt: Mediaconvert
                States:
                  Mediaconvert:
                    Type: Task
                    Resource: arn:aws:states:::lambda:invoke
                    Retry:
                      - ErrorEquals:
                          - Lambda.ServiceException
                          - Lambda.AWSLambdaException
                          - Lambda.SdkClientException
                          - Lambda.TooManyRequestsException
                        IntervalSeconds: 1
                        MaxAttempts: 3
                        BackoffRate: 2
                        JitterStrategy: FULL
                    End: true
                    Parameters:
                      FunctionName: !Ref mediaConvertName
                      Payload.$: $
            End: true
      DefinitionSubstitutions:
        TranscribeLambda: !Ref transcribeName
        MediaConvertLambda: !Ref mediaConvertName
      Name: StateMachine5b3433f1
      Type: STANDARD
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/VideoProcessingStepFunctionsRole
      Logging:
        Level: 'OFF'
        IncludeExecutionData: false
